version: '2'

services:       
  db:
    image: 'postgres:15.3'
    container_name: demo-postgresql
    expose:
     - 5432
    ports:
      - 5432:5432
    volumes:
      - ./backup:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres22
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  postgres:
    image: 'postgres:15.3'
    container_name: MyPostgres
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=elflab
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc